server:
  port: 7071
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/versity
    username: root
    password: root
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  feign.client.url.TestUrl: http://localhost:8093
  
#  mail:
#    host: smtp.office365.com
#    port: 587
#    username: support-obs@ojas-it.com
#    password: Ojas_OBS
#    properties:
#      mail: 
#        smtp: 
#          auth: true
#          starttls: 
#            enable: true


#subject: Timesheet Submission Status
#submit: has been submitted successfully and it is in pending for approval.
#accept: has been accepted successfully!
#reject: Please update and resubmit your timesheet.


#eureka:
# client: 
#  serviceUrl:
#   defaultZone: http://192.168.1.155:8089/eureka


#  server.port: 7006
#
#  spring: 
#   datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    jackson.serialization.FAIL_ON_EMPTY_BEANS: false
#    feign.client.url.TestUrl: http://192.168.0.106:8093/mail/set
#   mail:
#    host: smtp.gmail.com
#    port: 587
#    username: srikanth.naredla191726@gmail.com
#    password: Sequretek@47
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    
##  messageTransfer: "on"
##  fromNumber: 918688817726
##  token: 15c4f7bf48eb4304fa22b8f98b64cfe65db2918fb7321
##  msgPrefix: "ojas"
##  apiUrl: https://www.waboxapp.com/api/send/chat
#
#            